/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Clientes;
import Controlador.ConexionSQL;
import Modelo.Empleados;
import Modelo.Login;
import Modelo.Productos;
import Modelo.Proveedores;
import Modelo.Ventas;
import java.awt.Color;
import java.awt.FlowLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    private JDialog popup = new JDialog();
    private JLabel mensaje = new JLabel();
    private LocalDate fecha = LocalDate.now();
    private ConexionSQL sql = new ConexionSQL();
    private ArrayList proveedor = new ArrayList();
    private ArrayList empleado = new ArrayList();
    private DefaultTableModel Tablatodo = new DefaultTableModel();

    /*private Login login;
    private Empleados empleados;
    private Productos productos;
    private Proveedores proveedores;
    private Clientes clientes;
    private Ventas ventas;*/
    public Administrador() {
        mensaje.setVerticalTextPosition(JLabel.CENTER);

        popup.setLayout(new FlowLayout());
        popup.setSize(300, 100);
        popup.setLocation(280, 250);
        popup.setType(Type.UTILITY);
        popup.add(mensaje);

        initComponents();

        Cli6.setText(fecha.format(DateTimeFormatter.ISO_DATE));
        buttonGroup1.add(Clientes);
        buttonGroup1.add(Productos);
        buttonGroup1.add(Proveedor);
        buttonGroup1.add(Empleados);
        buttonGroup1.add(Login);

        actualizar();

    }

    private void actualizar() {
        Prod5.removeAllItems();
        Log4.removeAllItems();
        Prod5.addItem("Proveedor");
        Log4.addItem("Empleado");
        sql.Conexion();
        proveedor = sql.selectproveedor();

        for (int i = 0; i < proveedor.size(); i++) {
            Prod5.addItem(proveedor.get(i) + "-" + proveedor.get(i + 1));
            i++;
        }

        sql.Conexion();
        empleado = sql.selectempleado();
        for (int i = 0; i < empleado.size(); i++) {
            Log4.addItem(empleado.get(i) + "-" + empleado.get(i + 1) + " " + empleado.get(i + 2) + " " + empleado.get(i + 3));
            i += 3;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Tablas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Emp1 = new javax.swing.JTextField();
        Emp2 = new javax.swing.JTextField();
        Emp3 = new javax.swing.JTextField();
        Emp4 = new javax.swing.JTextField();
        Emp5 = new javax.swing.JTextField();
        Prod1 = new javax.swing.JTextField();
        Prod2 = new javax.swing.JTextField();
        Prod3 = new javax.swing.JTextField();
        Prod4 = new javax.swing.JTextField();
        Pro1 = new javax.swing.JTextField();
        Pro4 = new javax.swing.JTextField();
        Pro3 = new javax.swing.JTextField();
        Cli1 = new javax.swing.JTextField();
        Cli4 = new javax.swing.JTextField();
        Cli6 = new javax.swing.JTextField();
        Cli3 = new javax.swing.JTextField();
        Cli5 = new javax.swing.JTextField();
        Log1 = new javax.swing.JTextField();
        Log2 = new javax.swing.JTextField();
        Log4 = new javax.swing.JComboBox<>();
        Pro2 = new javax.swing.JTextField();
        Empleados = new javax.swing.JRadioButton();
        Productos = new javax.swing.JRadioButton();
        Proveedor = new javax.swing.JRadioButton();
        Clientes = new javax.swing.JRadioButton();
        Login = new javax.swing.JRadioButton();
        Btagregar = new javax.swing.JButton();
        Log3 = new javax.swing.JComboBox<>();
        Cli2 = new javax.swing.JTextField();
        Emp6 = new javax.swing.JTextField();
        Emp7 = new javax.swing.JTextField();
        Prod5 = new javax.swing.JComboBox<>();
        Btactualizar = new javax.swing.JButton();
        Bteliminar = new javax.swing.JButton();
        Btmostrar = new javax.swing.JButton();
        Idantiguo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        Tabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);

        Tablas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleados", "Login", "Clientes", "Productos", "Proveedores", "Ventas" }));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        Emp1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp1.setText("Nombres");
        Emp1.setToolTipText("Nombres");

        Emp2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp2.setText("Apellido paterno");
        Emp2.setToolTipText("Apellido paterno");

        Emp3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp3.setText("Apellido materno");
        Emp3.setToolTipText("Apellido materno");

        Emp4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp4.setText("Dirección");
        Emp4.setToolTipText("Dirección");

        Emp5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp5.setText("Telefono");
        Emp5.setToolTipText("Telefono");

        Prod1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prod1.setText("Nombre");
        Prod1.setToolTipText("Nombre");

        Prod2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prod2.setText("Precio");
        Prod2.setToolTipText("Precio");

        Prod3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prod3.setText("Codigo");
        Prod3.setToolTipText("Codigo");

        Prod4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prod4.setText("Cantidad");
        Prod4.setToolTipText("Codigo");

        Pro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pro1.setText("Nombre");
        Pro1.setToolTipText("Nombre");

        Pro4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pro4.setText("Telefono");
        Pro4.setToolTipText("Telefono");

        Pro3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pro3.setText("RFC");
        Pro3.setToolTipText("RFC");

        Cli1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli1.setText("Nombres");
        Cli1.setToolTipText("Nombres");

        Cli4.setEditable(false);
        Cli4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli4.setText("Tarjeta");
        Cli4.setToolTipText("Tarjeta");

        Cli6.setEditable(false);
        Cli6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli6.setText("Fecha Registro");
        Cli6.setToolTipText("Fecha Registro");
        Cli6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cli6ActionPerformed(evt);
            }
        });

        Cli3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli3.setText("Apellido materno");
        Cli3.setToolTipText("Apellido materno");

        Cli5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli5.setText("Puntos");
        Cli5.setToolTipText("Puntos");

        Log1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Log1.setText("Usuario");
        Log1.setToolTipText("Usuario");

        Log2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Log2.setText("Contraseña");
        Log2.setToolTipText("Contraseña");

        Log4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Log4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", " " }));
        Log4.setToolTipText("Empleado");

        Pro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pro2.setText("Dirección");
        Pro2.setToolTipText("Dirección");

        Empleados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Empleados.setText("Empleados");

        Productos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Productos.setText("Productos");

        Proveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Proveedor.setText("Proveedores");

        Clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Clientes.setText("Clientes");

        Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Login.setText("Login");

        Btagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btagregar.setText("Agregar");
        Btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtagregarActionPerformed(evt);
            }
        });

        Log3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Log3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puesto", "ADMIN", "EMPLE" }));
        Log3.setToolTipText("Puesto");

        Cli2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cli2.setText("Apellido paterno");
        Cli2.setToolTipText("Apellido paterno");

        Emp6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp6.setText("Sueldo");
        Emp6.setToolTipText("Sueldo");

        Emp7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emp7.setText("Edad");
        Emp7.setToolTipText("Edad");

        Prod5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prod5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", " " }));
        Prod5.setToolTipText("Proveedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pro1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Prod1)
                                .addGap(18, 18, 18)
                                .addComponent(Prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Prod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pro2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Log2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Log3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Log4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Btagregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Empleados)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Emp4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                            .addComponent(Emp1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Emp5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Emp6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Emp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Emp2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Emp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 100, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clientes)
                            .addComponent(Proveedor)
                            .addComponent(Productos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Pro3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pro4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Login)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cli4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cli5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cli6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cli1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cli2)
                                        .addGap(18, 18, 18)))
                                .addComponent(Cli3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Prod5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 110, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Empleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prod3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Prod5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(Proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(Clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cli3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cli2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cli6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cli5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Login)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Log2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Log4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Log3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btagregar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Cli2.getAccessibleContext().setAccessibleName("Apellido paterno");

        Btactualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btactualizar.setText("Actualizar");
        Btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtactualizarActionPerformed(evt);
            }
        });

        Bteliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bteliminar.setText("Eliminar");
        Bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BteliminarActionPerformed(evt);
            }
        });

        Btmostrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btmostrar.setText("Mostrar");
        Btmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmostrarActionPerformed(evt);
            }
        });

        Idantiguo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Idantiguo.setText("Id antiguo");
        Idantiguo.setToolTipText("Id antiguo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btmostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Idantiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(Bteliminar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btactualizar)
                    .addComponent(Bteliminar)
                    .addComponent(Btmostrar)
                    .addComponent(Idantiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtagregarActionPerformed
        // TODO add your handling code here:
        sql.Conexion();
        if (buttonGroup1.isSelected(Clientes.getModel())) {
            Random ran = new Random();
            fecha = LocalDate.now();

            String tarjeta = "" + Cli1.getText().charAt(0) + Cli2.getText().charAt(0) + Cli3.getText().charAt(0) + fecha.format(DateTimeFormatter.BASIC_ISO_DATE) + (10 + ran.nextInt(89));

            if (Cli5.getText().matches("[0-9]+")) {

                sql.agregarcliente(Cli1.getText(), Cli2.getText(), Cli3.getText(), tarjeta, fecha.format(DateTimeFormatter.BASIC_ISO_DATE), Integer.parseInt(Cli5.getText()));
                Cli1.setText("Nombres");
                Cli2.setText("Apellido Paterno");
                Cli3.setText("Apellido Materno");
                Cli4.setText(tarjeta);
                Cli5.setText("Puntos");
                Cli6.setText(fecha.format(DateTimeFormatter.ISO_DATE));

                mensaje.setText("Cliente Ingresado");
                mensaje.setForeground(Color.black);
                popup.setVisible(true);
            } else {
                mensaje.setText("Ingresar solo números en la casilla de puntos");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            }

        } else if (buttonGroup1.isSelected(Proveedor.getModel())) {
            if (Pro4.getText().matches("[0-9]+")) {

                sql.agregarproveedor(Pro1.getText(), Pro2.getText(), Integer.parseInt(Pro4.getText()), Pro3.getText());

                Pro1.setText("Nombre");
                Pro2.setText("Direccion");
                Pro4.setText("Telefono");
                Pro3.setText("RFC");
                actualizar();
                mensaje.setText("Proveedor Ingresado");
                mensaje.setForeground(Color.black);
                popup.setVisible(true);
            } else {
                mensaje.setText("Ingresar solo números en la casilla de telefono");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            }
        } else if (buttonGroup1.isSelected(Productos.getModel())) {
            if (Prod2.getText().matches("[0-9]+") && Prod3.getText().matches("[0-9]+") && Prod4.getText().matches("[0-9]+")) {

                sql.agregarproducto(Prod1.getText(), Float.parseFloat(Prod2.getText()), Integer.parseInt(Prod3.getText()), Integer.parseInt(Prod4.getText()), Integer.parseInt(String.valueOf(Prod5.getSelectedItem().toString().charAt(0))));

                Prod1.setText("Nombre");
                Prod2.setText("Precio");
                Prod3.setText("Codigo");
                Prod4.setText("Cantidad");

                mensaje.setText("Producto Ingresado");
                mensaje.setForeground(Color.black);
                popup.setVisible(true);
            } else {
                mensaje.setText("Ingresar solo números en las casillas precio, codigo y cantidad");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            }
        } else if (buttonGroup1.isSelected(Login.getModel())) {
            System.out.println(Integer.parseInt(String.valueOf(Log4.getSelectedItem().toString().charAt(0))));
            sql.agregarlogin(Log1.getText(), Log2.getText(), Log3.getSelectedItem().toString(), Integer.parseInt(String.valueOf(Log4.getSelectedItem().toString().charAt(0))));

            Log1.setText("Usuario");
            Log2.setText("Contraseña");

            mensaje.setText("Login Ingresado");
            mensaje.setForeground(Color.black);
            popup.setVisible(true);
        } else if (buttonGroup1.isSelected(Empleados.getModel())) {
            if (Emp5.getText().matches("[0-9]+") && Emp6.getText().matches("[0-9]+") && Emp7.getText().matches("[0-9]+")) {

                sql.agregarempleado(Emp1.getText(), Emp2.getText(), Emp3.getText(), Emp4.getText(), Integer.parseInt(Emp5.getText()), Integer.parseInt(Emp6.getText()), Integer.parseInt(Emp7.getText()));

                Emp1.setText("Nombres");
                Emp2.setText("Apellido Paterno");
                Emp3.setText("Apellido Materno");
                Emp4.setText("Dirección");
                Emp5.setText("Telefono");
                Emp6.setText("Sueldo");
                Emp7.setText("Edad");
                actualizar();
                mensaje.setText("Empleado Ingresado");
                mensaje.setForeground(Color.black);
                popup.setVisible(true);
            } else {
                mensaje.setText("Ingresar solo números en las casillas de telefono, sueldo y edad");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            }
        } else {
            mensaje.setText("No se ha seleccionado tabla");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        }
    }//GEN-LAST:event_BtagregarActionPerformed

    private void BtmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmostrarActionPerformed
        // TODO add your handling code here:
        sql.Conexion();

        Tablatodo = (DefaultTableModel) Tabla.getModel();
        Tablatodo.setColumnCount(0);
        Tablatodo.setRowCount(0);
        if (Tablas.getSelectedItem().toString().equals("Empleados")) {
            Tabla.removeAll();
            ArrayList emp = sql.tablaempleado();

            Tablatodo.addColumn("ID");
            Tablatodo.addColumn("Nombres");
            Tablatodo.addColumn("Apellido Paterno");
            Tablatodo.addColumn("Apellido Materno");
            Tablatodo.addColumn("Dirección");
            Tablatodo.addColumn("Telefono");
            Tablatodo.addColumn("Sueldo");
            Tablatodo.addColumn("Edad");

            Object emple[][] = new Object[emp.size() / 8][8];
            int k = 0;
            for (int i = 0; i < emp.size() / 8; i++) {

                for (int j = 0; j < 8; j++) {
                    emple[i][j] = emp.get(k);
                    k++;
                }
                Tablatodo.addRow(emple[i]);
            }
            Tabla.setModel(Tablatodo);
        }
        if (Tablas.getSelectedItem().toString().equals("Ventas")) {
            Tabla.removeAll();

            ArrayList venta = sql.tablaventas();

            Tablatodo.addColumn("Venta#");
            Tablatodo.addColumn("ID_Producto");
            Tablatodo.addColumn("Cantidad");
            Tablatodo.addColumn("Precio Total");
            Tablatodo.addColumn("Fecha");
            Tablatodo.addColumn("ID_Empleado");
            Tablatodo.addColumn("ID_Cliente");
            Tablatodo.addColumn("Tipo Pago");

            Object vent[][] = new Object[venta.size() / 8][8];
            int k = 0;
            for (int i = 0; i < venta.size() / 8; i++) {

                for (int j = 0; j < 8; j++) {
                    vent[i][j] = venta.get(k);
                    k++;
                }
                Tablatodo.addRow(vent[i]);
            }
            Tabla.setModel(Tablatodo);
        }
        if (Tablas.getSelectedItem().toString().equals("Productos")) {
            Tabla.removeAll();
            ArrayList producto = sql.tablaproductos();

            Tablatodo.addColumn("ID");
            Tablatodo.addColumn("Nombres");
            Tablatodo.addColumn("Precio");
            Tablatodo.addColumn("Codigo");
            Tablatodo.addColumn("Cantidad");
            Tablatodo.addColumn("ID_Proveedor");

            Object prod[][] = new Object[producto.size() / 6][6];
            int k = 0;
            for (int i = 0; i < producto.size() / 6; i++) {

                for (int j = 0; j < 6; j++) {
                    prod[i][j] = producto.get(k);
                    k++;
                }
                Tablatodo.addRow(prod[i]);
            }
            Tabla.setModel(Tablatodo);
        }
        if (Tablas.getSelectedItem().toString().equals("Proveedores")) {
            Tabla.removeAll();
            ArrayList proveedor = sql.tablaproveedor();

            Tablatodo.addColumn("ID");
            Tablatodo.addColumn("Nombre");
            Tablatodo.addColumn("Dirección");
            Tablatodo.addColumn("Telefono");
            Tablatodo.addColumn("RFC");

            Object prov[][] = new Object[proveedor.size() / 5][5];
            int k = 0;
            for (int i = 0; i < proveedor.size() / 5; i++) {

                for (int j = 0; j < 5; j++) {
                    prov[i][j] = proveedor.get(k);
                    k++;
                }
                Tablatodo.addRow(prov[i]);
            }
            Tabla.setModel(Tablatodo);
        }
        if (Tablas.getSelectedItem().toString().equals("Clientes")) {
            Tabla.removeAll();
            ArrayList cliente = sql.tablaclientes();

            Tablatodo.addColumn("ID");
            Tablatodo.addColumn("Nombres");
            Tablatodo.addColumn("Apellido Paterno");
            Tablatodo.addColumn("Apellido Materno");
            Tablatodo.addColumn("Tarjeta");
            Tablatodo.addColumn("Registro");
            Tablatodo.addColumn("Puntos");

            Object cli[][] = new Object[cliente.size() / 7][7];
            int k = 0;
            for (int i = 0; i < cliente.size() / 7; i++) {

                for (int j = 0; j < 7; j++) {
                    cli[i][j] = cliente.get(k);
                    k++;
                }
                Tablatodo.addRow(cli[i]);
            }
            Tabla.setModel(Tablatodo);
        }
        if (Tablas.getSelectedItem().toString().equals("Login")) {
            Tabla.removeAll();
            ArrayList Login = sql.tablalogin();

            Tablatodo.addColumn("ID");
            Tablatodo.addColumn("Usuario");
            Tablatodo.addColumn("Contraseña");
            Tablatodo.addColumn("Puesto");
            Tablatodo.addColumn("ID_Empleado");

            Object log[][] = new Object[Login.size() / 5][5];
            int k = 0;
            for (int i = 0; i < Login.size() / 5; i++) {

                for (int j = 0; j < 5; j++) {
                    log[i][j] = Login.get(k);
                    k++;
                }
                Tablatodo.addRow(log[i]);
            }
            Tabla.setModel(Tablatodo);
        }

    }//GEN-LAST:event_BtmostrarActionPerformed

    private void BteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BteliminarActionPerformed
        // TODO add your handling code here:
        sql.Conexion();
        if (Tablas.getSelectedItem().toString().equals("Empleados")) {

            try {
                sql.eliminarempleado((int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println("Eliminada la fila " + Tabla.getSelectedRow());
                Tablatodo.removeRow(Tabla.getSelectedRow());

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        if (Tablas.getSelectedItem().toString().equals("Ventas")) {

            int ventaselec = (int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0);
            try {

                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));

                for (int i = 0; i < Tablatodo.getRowCount(); i++) {
                    if ((int) Tablatodo.getValueAt(i, 0) == ventaselec) {
                        Tablatodo.removeRow(i);
                        System.out.println("Eliminada la fila " + i);
                        i--;
                    }
                }
                sql.eliminarventa(ventaselec);

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        if (Tablas.getSelectedItem().toString().equals("Productos")) {

            try {
                sql.eliminarproducto((int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println("Eliminada la fila " + Tabla.getSelectedRow());
                Tablatodo.removeRow(Tabla.getSelectedRow());

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        if (Tablas.getSelectedItem().toString().equals("Proveedores")) {

            try {
                sql.eliminarproveedor((int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println("Eliminada la fila " + Tabla.getSelectedRow());
                Tablatodo.removeRow(Tabla.getSelectedRow());

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        if (Tablas.getSelectedItem().toString().equals("Clientes")) {

            try {
                sql.eliminarcliente((int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println("Eliminada la fila " + Tabla.getSelectedRow());
                Tablatodo.removeRow(Tabla.getSelectedRow());

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        if (Tablas.getSelectedItem().toString().equals("Login")) {

            try {
                sql.eliminarlogin((int) Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0));
                System.out.println("Eliminada la fila " + Tabla.getSelectedRow());
                Tablatodo.removeRow(Tabla.getSelectedRow());

            } catch (Exception e) {
                System.out.println("No existe esa fila");
            }
        }
        actualizar();
    }//GEN-LAST:event_BteliminarActionPerformed

    private void BtactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtactualizarActionPerformed
        // TODO add your handling code here:
        if (Tablas.getSelectedItem().toString().equals("Ventas")) {
            mensaje.setText("No se pueden modificar las ventas");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else {
            if (Idantiguo.getText().matches("[0-9]+")) {
                sql.Conexion();
                if (Tablas.getSelectedItem().toString().equals("Empleados")) {
                    sql.modificarempleado(Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0).toString()), Tablatodo.getValueAt(Tabla.getSelectedRow(), 1).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 2).toString(), Tablatodo.getValueAt(Tabla.getSelectedRow(), 3).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 4).toString(), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 5).toString()),
                            Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 6).toString()), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 7).toString()), Integer.parseInt(Idantiguo.getText()));
                }
                if (Tablas.getSelectedItem().toString().equals("Productos")) {
                    sql.modificarproducto(Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0).toString()), Tablatodo.getValueAt(Tabla.getSelectedRow(), 1).toString(),
                            Float.parseFloat(Tablatodo.getValueAt(Tabla.getSelectedRow(), 2).toString()), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 3).toString()),
                            Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 4).toString()), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 5).toString()), Integer.parseInt(Idantiguo.getText()));
                }
                if (Tablas.getSelectedItem().toString().equals("Proveedores")) {
                    sql.modificarproveedor(Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0).toString()), Tablatodo.getValueAt(Tabla.getSelectedRow(), 1).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 2).toString(), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 3).toString()),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 4).toString(), Integer.parseInt(Idantiguo.getText()));
                }
                if (Tablas.getSelectedItem().toString().equals("Clientes")) {
                    sql.modificarcliente(Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0).toString()), Tablatodo.getValueAt(Tabla.getSelectedRow(), 1).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 2).toString(), Tablatodo.getValueAt(Tabla.getSelectedRow(), 3).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 4).toString(), Tablatodo.getValueAt(Tabla.getSelectedRow(), 5).toString(),
                            Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 6).toString()), Integer.parseInt(Idantiguo.getText()));
                }
                if (Tablas.getSelectedItem().toString().equals("Login")) {
                    sql.modificarlogin(Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 0).toString()), Tablatodo.getValueAt(Tabla.getSelectedRow(), 1).toString(),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 2).toString(), Integer.parseInt(Tablatodo.getValueAt(Tabla.getSelectedRow(), 4).toString()),
                            Tablatodo.getValueAt(Tabla.getSelectedRow(), 3).toString(), Integer.parseInt(Idantiguo.getText()));
                }
            } else {
                mensaje.setText("Ingresa solo numeros como Id antiguo");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            }
        }
        actualizar();
        Idantiguo.setText("Id antiguo");
    }//GEN-LAST:event_BtactualizarActionPerformed

    private void Cli6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cli6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cli6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btactualizar;
    private javax.swing.JButton Btagregar;
    private javax.swing.JButton Bteliminar;
    private javax.swing.JButton Btmostrar;
    private javax.swing.JTextField Cli1;
    private javax.swing.JTextField Cli2;
    private javax.swing.JTextField Cli3;
    private javax.swing.JTextField Cli4;
    private javax.swing.JTextField Cli5;
    private javax.swing.JTextField Cli6;
    private javax.swing.JRadioButton Clientes;
    private javax.swing.JTextField Emp1;
    private javax.swing.JTextField Emp2;
    private javax.swing.JTextField Emp3;
    private javax.swing.JTextField Emp4;
    private javax.swing.JTextField Emp5;
    private javax.swing.JTextField Emp6;
    private javax.swing.JTextField Emp7;
    private javax.swing.JRadioButton Empleados;
    private javax.swing.JTextField Idantiguo;
    private javax.swing.JTextField Log1;
    private javax.swing.JTextField Log2;
    private javax.swing.JComboBox<String> Log3;
    private javax.swing.JComboBox<String> Log4;
    private javax.swing.JRadioButton Login;
    private javax.swing.JTextField Pro1;
    private javax.swing.JTextField Pro2;
    private javax.swing.JTextField Pro3;
    private javax.swing.JTextField Pro4;
    private javax.swing.JTextField Prod1;
    private javax.swing.JTextField Prod2;
    private javax.swing.JTextField Prod3;
    private javax.swing.JTextField Prod4;
    private javax.swing.JComboBox<String> Prod5;
    private javax.swing.JRadioButton Productos;
    private javax.swing.JRadioButton Proveedor;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox<String> Tablas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
