/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Clientes;
import Controlador.ConexionSQL;
import Modelo.Productos;
import Modelo.Ventas;
import java.awt.Color;
import java.awt.FlowLayout;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ConexionSQL sql;
    private String prod[] = new String[4];
    private JDialog popup = new JDialog();
    private JLabel mensaje = new JLabel();
    private DefaultTableModel TablaTicket = new DefaultTableModel();
    private float total = 0;
    private int puntosmenos = 0;
    private LocalDate fecha = LocalDate.now();
    private LocalTime hora = LocalTime.now();
    private Timer Hora;
    private String us, con;
    private ArrayList<Integer> prodpunto = new ArrayList<Integer>();
    private Vector<String> prodpuntos = new Vector<String>();
    private List nopuntos;

    /*private Productos productos;
    private Clientes clientes;
    private Ventas ventas;*/
    public Principal(String us, String con) {
        this.sql = new ConexionSQL();
        this.us = us;
        this.con = con;
        //System.out.println(fecha);

        mensaje.setVerticalTextPosition(JLabel.CENTER);

        popup.setLayout(new FlowLayout());
        popup.setSize(300, 100);
        popup.setLocation(280, 250);
        popup.setType(Type.UTILITY);
        popup.add(mensaje);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Ticket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txtcantidad = new javax.swing.JTextField();
        Btagregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txtprod = new javax.swing.JTextField();
        Txtalmacen = new javax.swing.JTextField();
        Btbuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Txtpagar = new javax.swing.JTextField();
        Btpagar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Bteliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Txttarjeta = new javax.swing.JTextField();
        Bttarjeta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Txtnom = new javax.swing.JTextField();
        Txtap = new javax.swing.JTextField();
        Txtam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        Btcliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lprodpuntos = new javax.swing.JList<>();
        Btcanjear = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Cbpago = new javax.swing.JComboBox<>();
        Totalbruto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comercializadora Mexícana");
        setPreferredSize(new java.awt.Dimension(1365, 720));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        Ticket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ticket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Codigo", "Cantidad", "Precio Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ticket.setName(""); // NOI18N
        Ticket.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Ticket);
        if (Ticket.getColumnModel().getColumnCount() > 0) {
            Ticket.getColumnModel().getColumn(1).setMaxWidth(75);
            Ticket.getColumnModel().getColumn(2).setMaxWidth(50);
            Ticket.getColumnModel().getColumn(3).setMaxWidth(100);
            Ticket.getColumnModel().getColumn(4).setMaxWidth(75);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo");

        Txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad");

        Txtcantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Btagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btagregar.setText("Agregar");
        Btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtagregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Producto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Almacen");

        Txtprod.setEditable(false);
        Txtprod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Txtalmacen.setEditable(false);
        Txtalmacen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Btbuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btbuscar.setText("Buscar");
        Btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total A Pagar");

        Txtpagar.setEditable(false);
        Txtpagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txtpagar.setText("0.0");

        Btpagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btpagar.setText("Pagar");
        Btpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtpagarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Eliminar Entrada ");

        Bteliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bteliminar.setText("Eliminar");
        Bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BteliminarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("$");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Txttarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Bttarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bttarjeta.setText("Buscar");
        Bttarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttarjetaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nombre");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Puntos En Tarjeta");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Puntos Por Compra");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("# Tarjeta Virtual");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Nuevo Cliente");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Nombres");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Apellido Paterno");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Apellido Materno");

        Txtnom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Txtap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Txtam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("# Tarjeta Virtual");

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Btcliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btcliente.setText("Agregar");
        Btcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtclienteActionPerformed(evt);
            }
        });

        Lprodpuntos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(Lprodpuntos);

        Btcanjear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btcanjear.setText("Canjear");
        Btcanjear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtcanjearActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("puntos ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel17)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(Btcliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btcanjear)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel19))))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7))
                            .addComponent(Txttarjeta)
                            .addComponent(Bttarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txttarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bttarjeta)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btcanjear)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btcliente))
                .addGap(18, 18, 18))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Agregar Entrada");

        Cbpago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Pago", "Efectivo", "Tarjeta", "Puntos" }));
        Cbpago.setToolTipText("Tipo de Pago");

        Totalbruto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Totalbruto.setText("Total bruto");
        Totalbruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalbrutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Btagregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Btbuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Txtcantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Txtalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Txtprod, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(Cbpago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(Txtpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Totalbruto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btbuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btagregar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bteliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(Totalbruto)
                                .addGap(74, 74, 74)
                                .addComponent(Cbpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(Txtpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Btpagar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbuscarActionPerformed
        // TODO add your handling code here:
        //System.out.println(jTextField3.getText()+" "+jTextField4.getText());
        sql.Conexion();
        if (Txtcodigo.getText().equals("")) {
            mensaje.setText("No se ha agregado un producto");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else {
            prod = sql.buscarprod(Txtcodigo.getText());
            if (prod[0] == "0") {
                mensaje.setText("Codigo erroneo: Ese producto no esta registrado");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            } else {
                Txtprod.setText(prod[1]);
                Txtalmacen.setText(prod[3]);
            }
        }
    }//GEN-LAST:event_BtbuscarActionPerformed

    private void BtagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtagregarActionPerformed
        // TODO add your handling code here:
        
        //Txtpagar.setText("" + total);
        if (Txtprod.getText().equals("")) {
            mensaje.setText("No se ha verificado producto existente");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else if (Txtcantidad.getText().equals("")) {
            mensaje.setText("No se ha ingresado cantidad de producto");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else if (Integer.parseInt(Txtcantidad.getText()) > Integer.parseInt(Txtalmacen.getText())) {
            mensaje.setText("No hay suficientes piezas en el almacen");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else if (!Txtprod.getText().equals("") && !Txtcantidad.getText().equals("")) {

            TablaTicket = (DefaultTableModel) Ticket.getModel();

            /*ArrayList ticket= new ArrayList();

            ticket.add(prod[1]);
            ticket.add(jTextField1.getText());
            ticket.add(jTextField2.getText());
            ticket.add(prod[2]);
            System.out.println(Float.parseFloat(prod[2])*Float.parseFloat(jTextField2.getText()));
            ticket.add(Float.parseFloat(prod[2])*Float.parseFloat(jTextField2.getText()));*/
            Object nprod[] = new Object[5];

            /*nprod[0]=ticket.get(0);
            nprod[1]=ticket.get(1);
            nprod[2]=ticket.get(2);
            nprod[3]=ticket.get(3);
            nprod[4]=ticket.get(4);*/
            //nprod[0]=Ticket.getRowCount()+1;
            nprod[0] = prod[1];
            nprod[1] = Txtcodigo.getText();
            nprod[2] = Txtcantidad.getText();
            nprod[3] = prod[2];
            nprod[4] = Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText());

            TablaTicket.addRow(nprod);

            Ticket.setModel(TablaTicket);

            /*if (Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText()) <= 100 && Integer.parseInt(jTextField3.getText()) >= (int) (Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText())) * 3) {

                prodpunto.add((int) (Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText())) * 3);
                prodpuntos.add(TablaTicket.getRowCount() + "-" + nprod[0].toString() + " X" + nprod[2] + " por " + (int) (Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText())) * 3 + " puntos");
            }*/
            //Ticket.getSelectedRow();
            //total += Float.parseFloat(prod[2]) * Float.parseFloat(Txtcantidad.getText());
            //puntos();
            total = 0;
            for (int j = 0; j < Ticket.getRowCount(); j++) {
                total += Float.parseFloat(Ticket.getValueAt(j, 4).toString());

            }
            Txtcodigo.setText("");
            Txtcantidad.setText("");
            Txtprod.setText("");
            Txtalmacen.setText("");
            Txtpagar.setText("" + total);

            puntos();
        }

    }//GEN-LAST:event_BtagregarActionPerformed

    private void BteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BteliminarActionPerformed
        // TODO add your handling code here:
        try {
            //total -= (float) TablaTicket.getValueAt(Ticket.getSelectedRow(), 4);
            System.out.println("Eliminada la fila" + Ticket.getSelectedRow());
            TablaTicket.removeRow(Ticket.getSelectedRow());
            puntos();
            Txtpagar.setText("" + total);

        } catch (Exception e) {
            System.out.println("No existe esa fila");
        }
        //Ticket.removeRowSelectionInterval(Integer.parseInt(jTextField6.getText())-1,Integer.parseInt(jTextField6.getText()));
    }//GEN-LAST:event_BteliminarActionPerformed

    private void BttarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttarjetaActionPerformed
        // TODO add your handling code here:
        sql.Conexion();
        if (Txttarjeta.getText().equals("")) {
            mensaje.setText("No se ha agregado el número de tarjeta");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else {
            String cliente[] = sql.buscarXtarjeta(Txttarjeta.getText());
            Lprodpuntos.removeAll();
            prodpuntos.removeAllElements();
            prodpunto.clear();
            if (cliente[0].equals("0")) {
                mensaje.setText(" Número de Tarjeta erronea");
                mensaje.setForeground(Color.red);
                popup.setVisible(true);
            } else {
                jTextField2.setText(cliente[0]);
                jTextField3.setText(cliente[1]);
                int maxpuntos = 0,j=0;
                for (int i = 0; i < TablaTicket.getRowCount(); i++) {
                    if ((int) Float.parseFloat(Ticket.getValueAt(i, 4).toString()) <= 100 && (int) Float.parseFloat(jTextField3.getText()) >= (int) Float.parseFloat(Ticket.getValueAt(i, 4).toString()) * 3) {
                        try {
                            prodpunto.add((int) Float.parseFloat(Ticket.getValueAt(i, 4).toString()) * 3);
                            maxpuntos += prodpunto.get(j);
                            j++;
                            System.out.println("maxpuntos " + maxpuntos + " puntos cliente " + Integer.parseInt(jTextField3.getText()));
                            if (maxpuntos >= Integer.parseInt(jTextField3.getText())) //i=TablaTicket.getRowCount()+11;
                            {
                                break;
                            }
                            prodpuntos.add(i + "-" + Ticket.getValueAt(i, 0) + " X" + Ticket.getValueAt(i, 2) + " por " + (int) Float.parseFloat(Ticket.getValueAt(i, 4).toString()) * 3 + " puntos");
                        } catch (Exception e) {
                            System.out.println("" + e);
                        }
                    }

                }
                puntos();
                Lprodpuntos.setListData(prodpuntos);
            }
        }

        sql.cerrarConexion();
    }//GEN-LAST:event_BttarjetaActionPerformed

    private void BtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtclienteActionPerformed
        // TODO add your handling code here:
        sql.Conexion();
        if (Txtnom.getText().equals("")) {
            mensaje.setText("No se ha ingresado el Nombre");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else if (Txtap.getText().equals("")) {
            mensaje.setText("No se ha ingresado el Apellido Paterno");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else if (Txtam.getText().equals("")) {
            mensaje.setText("No se ha ingresado el Apellido Materno");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        } else {
            Random ran = new Random();
            fecha = LocalDate.now();

            String tarjeta = "" + Txtnom.getText().charAt(0) + Txtap.getText().charAt(0) + Txtam.getText().charAt(0) + fecha.format(DateTimeFormatter.BASIC_ISO_DATE) + (10 + ran.nextInt(89));

            sql.agregarcliente(Txtnom.getText(), Txtap.getText(), Txtam.getText(), tarjeta, fecha.format(DateTimeFormatter.BASIC_ISO_DATE), 0);

            jTextField8.setText(tarjeta);
            Txtnom.setText("");
            Txtap.setText("");
            Txtam.setText("");
            Txttarjeta.setText(tarjeta);

            mensaje.setText("Cliente ingresado");
            mensaje.setForeground(Color.black);
            popup.setVisible(true);

            System.out.println(tarjeta);
        }

    }//GEN-LAST:event_BtclienteActionPerformed

    private void BtpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtpagarActionPerformed
        // TODO add your handling code here:
        sql.Conexion();
        if (!Cbpago.getItemAt(Cbpago.getSelectedIndex()).equals("Tipo de Pago")) {

            int venta = sql.ultimaventa(),j=0;
            fecha = LocalDate.now();
            hora = LocalTime.now();
            
            for (int i = 0; i < Ticket.getRowCount(); i++) {
                if (!Txttarjeta.getText().equalsIgnoreCase("")) {

                    try {
                        System.out.println("nopuntos char at" + Integer.parseInt(String.valueOf(nopuntos.get(j).toString().charAt(0))));
                        if (Integer.parseInt(String.valueOf(nopuntos.get(j).toString().charAt(0))) == i) {
                            j++;
                            sql.agregarventa("Puntos", venta, (String) Ticket.getValueAt(i, 1), (String) Ticket.getValueAt(i, 2), (float) Ticket.getValueAt(i, 4), fecha.format(DateTimeFormatter.ISO_DATE) + " " + hora.format(DateTimeFormatter.ISO_TIME), Txttarjeta.getText(), us, con);
                        } else {
                            sql.agregarventa(Cbpago.getItemAt(Cbpago.getSelectedIndex()), venta, (String) Ticket.getValueAt(i, 1), (String) Ticket.getValueAt(i, 2), (float) Ticket.getValueAt(i, 4), fecha.format(DateTimeFormatter.ISO_DATE) + " " + hora.format(DateTimeFormatter.ISO_TIME), Txttarjeta.getText(), us, con);
                        }
                    } catch (Exception e) {
                        System.out.println("" + e);
                        sql.agregarventa(Cbpago.getItemAt(Cbpago.getSelectedIndex()), venta, (String) Ticket.getValueAt(i, 1), (String) Ticket.getValueAt(i, 2), (float) Ticket.getValueAt(i, 4), fecha.format(DateTimeFormatter.ISO_DATE) + " " + hora.format(DateTimeFormatter.ISO_TIME), Txttarjeta.getText(), us, con);
                    }

                } else {
                    sql.agregarventa(Cbpago.getItemAt(Cbpago.getSelectedIndex()), venta, (String) Ticket.getValueAt(i, 1), (String) Ticket.getValueAt(i, 2), (float) Ticket.getValueAt(i, 4), fecha.format(DateTimeFormatter.ISO_DATE) + " " + hora.format(DateTimeFormatter.ISO_TIME), "NEC0000000000", us, con);
                }
                System.out.println(Ticket.getRowCount());
            }
            sql.maspuntos(puntos(), Txttarjeta.getText());
            sql.menospuntos(puntosmenos, Txttarjeta.getText());
            sql.cerrarConexion();
            Txtpagar.setText("0.0");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            Txttarjeta.setText("");
            total = 0;
            Cbpago.setSelectedIndex(0);
            Lprodpuntos.removeAll();

            for (int i = 0; i < Ticket.getRowCount() + 3; i++) {
                TablaTicket.removeRow(0);
            }
        } else {
            mensaje.setText("Selecciona un tipo de pago");
            mensaje.setForeground(Color.red);
            popup.setVisible(true);
        }
    }//GEN-LAST:event_BtpagarActionPerformed

    private void BtcanjearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtcanjearActionPerformed
        // TODO add your handling code here:
        total = 0;
        for (int j = 0; j < Ticket.getRowCount(); j++) {
            total += Float.parseFloat(Ticket.getValueAt(j, 4).toString());
        }

        puntosmenos = 0;
        nopuntos = Lprodpuntos.getSelectedValuesList();

        //System.out.println(total);
        //prodpunto
        if (nopuntos.size() != Ticket.getRowCount()) {
            for (int j = 0; j < nopuntos.size(); j++) {
                try {
                    puntosmenos += prodpunto.get(j);
                    System.out.println("puntosmenos" + puntosmenos);
                    total -= Float.parseFloat(Ticket.getValueAt(Integer.parseInt(String.valueOf(nopuntos.get(j).toString().charAt(0))), 4).toString());
                    //System.out.println(Float.parseFloat(Ticket.getValueAt(Integer.parseInt(String.valueOf(nopuntos.get(i).toString().charAt(0))), 4).toString()));
                    System.out.println(total);
                } catch (Exception e) {
                    System.out.println("" + e);
                }
                //System.out.println(total);
            }
        } else {
            for (int j = 0; j < nopuntos.size(); j++) {
                try {
                    puntosmenos += prodpunto.get(j);
                    System.out.println("puntosmenos" + puntosmenos);

                } catch (Exception e) {
                    System.out.println("" + e);
                }
                //System.out.println(total);
            }
            total = 0;
        }
        puntos();
        Txtpagar.setText("" + total);
    }//GEN-LAST:event_BtcanjearActionPerformed

    private void TotalbrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalbrutoActionPerformed
        // TODO add your handling code here:
        total = 0;
        for (int j = 0; j < Ticket.getRowCount(); j++) {
            total += Float.parseFloat(Ticket.getValueAt(j, 4).toString());

        }
        System.out.println("Total bruto"+total);
        Txtpagar.setText(""+total);
    }//GEN-LAST:event_TotalbrutoActionPerformed

    private int puntos() {
        int puntos = 1, i = 1;

        //total = 0;
        //puntosmenos = 0;
        //nopuntos.clear();
        //int nopuntos[]=Lprodpuntos.getSelectedIndices();
        Txtpagar.setText("" + total);
        if (!Txttarjeta.getText().equals("")) {
            while ((8 * puntos) <= (int) Float.parseFloat(Txtpagar.getText())) {
                i = 8 * puntos;
                puntos++;
                //System.out.println(puntos);
            }
            jTextField4.setText("" + (puntos - 1));
            System.out.println("Total: " + Txtpagar.getText() + " Equivale a " + (puntos - 1) + " puntos");
            return puntos - 1;
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btagregar;
    private javax.swing.JButton Btbuscar;
    private javax.swing.JButton Btcanjear;
    private javax.swing.JButton Btcliente;
    private javax.swing.JButton Bteliminar;
    private javax.swing.JButton Btpagar;
    private javax.swing.JButton Bttarjeta;
    private javax.swing.JComboBox<String> Cbpago;
    private javax.swing.JList<String> Lprodpuntos;
    private javax.swing.JTable Ticket;
    private javax.swing.JButton Totalbruto;
    private javax.swing.JTextField Txtalmacen;
    private javax.swing.JTextField Txtam;
    private javax.swing.JTextField Txtap;
    private javax.swing.JTextField Txtcantidad;
    private javax.swing.JTextField Txtcodigo;
    private javax.swing.JTextField Txtnom;
    private javax.swing.JTextField Txtpagar;
    private javax.swing.JTextField Txtprod;
    private javax.swing.JTextField Txttarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
